### PR TITLE
Remove prop-types peerDep; 5.3.1 release

### LINKED ISSUE #174: Breaking peer dependency change in minor version
In https://github.com/brigade/react-waypoint/commit/836c24e3818f490aa2ebecf491cb9840f627918e a peer dependency on `"prop-types": "^15.0.0"` was added and this change made its way into `5.3.0`. This is a breaking change and causes the following error to be thrown `Uncaught Error: Cannot find module "prop-types"`.

### PR DESCRIPTION
**Pull request by jmeas**
Rather than revert the 4 commits in #172 (most of which are changes that we _do_ want), I just undid the part that was breaking peoples' builds.

Let me know how this looks, and I'll merge and release. Working on the 6.0.0 branch now (which will just `revert` fca1ebb )

Resolves #174

### CODE REVIEW

**Comment by trotzig** [comment]
Merge at will. :)

**Comment by jmeas** [comment]
Sorry, got caught in a meeting at work. Mergin' now.
